franklin/config/settings/base.py
franklin/core/urls.py
franklin/core/views.py
franklin/github/views.py
franklin/users/models.py

This connects to istrategylabs/franklin#93

Fixed bugs with save oAuth tokens and API docs

---

franklin/builder/serializers.py
franklin/config/settings/base.py
franklin/github/views.py
franklin/users/migrations/0003_userdetails_sites.py
franklin/users/models.py

Active repos user has permission to endpoint

---

franklin/config/settings/base.py
franklin/core/urls.py
franklin/github/views.py
requirements.txt

Rest endpoint to complete github oauth2 login from client side. Takes github client code and returns the github token. Afterwards this token will we used to get the franklin token.

Dashboard GitHub login

---

franklin/core/urls.py
franklin/github/views.py
franklin/users/models.py

New endpoint for ALL repos a user can act on

---

franklin/builder/migrations/0016_auto_20151222_1311.py
franklin/builder/models.py

Environments have a url on creation, regardless of current deploy

---

franklin/core/urls.py
franklin/github/views.py

Endpoint to delete existing repo

---

franklin/core/urls.py
franklin/github/views.py

Delete repo refactor

---

README.md
franklin/builder/models.py
franklin/builder/tests.py

Path is now relative and only users github_id/git_hash

---

franklin/builder/models.py
franklin/core/helpers.py
franklin/github/views.py
requirements.txt

Connected to istrategylabs/franklin#87

Generate deploy keys for registered repos

---

franklin/builder/migrations/0017_auto_20160216_1953.py
franklin/builder/models.py
franklin/builder/serializers.py
franklin/core/helpers.py
franklin/github/api.py
franklin/github/tests.py
franklin/github/views.py

Cleanup Github resources on site delete

---

franklin/builder/models.py
franklin/builder/serializers.py
franklin/builder/tests.py
franklin/core/urls.py
franklin/github/api.py
franklin/github/views.py

Deploy now endpoint

---

franklin/builder/models.py
franklin/github/api.py
franklin/github/views.py

Default environment should listen for default branch webhooks

---

franklin/core/urls.py
franklin/github/views.py

Endpoint to create and delete environments

---

franklin/core/urls.py
franklin/github/views.py

Promote environment

---

franklin/builder/models.py
franklin/builder/serializers.py
franklin/github/views.py

Cleaned up some of the API response details

---

README.md
franklin/builder/models.py
franklin/builder/serializers.py
franklin/github/views.py

Environment bugs found while testing dashboard

---

franklin/builder/models.py
franklin/builder/serializers.py
franklin/core/urls.py
franklin/github/views.py

Connected to #98 
GET `/repos/[github_id]` has been moved to `/projects/[github_id]`
DELETE `/repos/[github_id]` has been moved to `/projects/[github_id]`

Refactor of project details payload

---

franklin/github/serializers.py

Github API changed webhook messages

---

franklin/builder/tests.py
franklin/core/urls.py
franklin/github/tests.py
franklin/github/views.py

Connected to #103 
POST `/repos/[github_id]/environments` no longer exists
DELETE `/repos/[github_id]/environments` no longer exists
Tests have be fixed based on recent changes.

Removed environment create/delete endpoint. Fixed Tests.

---

franklin/core/urls.py
franklin/users/views.py

Connected to #111
GET `/user` will return json with the username.

Get User Details Endpoint

---

docker-compose.yml
franklin/builder/models.py
franklin/builder/tests.py
franklin/builder/views.py
franklin/core/exceptions.py
franklin/core/helpers.py
franklin/core/tests.py
franklin/github/api.py
franklin/github/views.py

Refactor exception handling

---

franklin/builder/serializers.py
franklin/core/exceptions.py
franklin/core/helpers.py
franklin/core/urls.py
franklin/core/views.py
franklin/github/api.py
franklin/github/permissions.py
franklin/github/serializers.py
franklin/github/views.py
franklin/users/tests.py

Testing and bug fixing

---

franklin/builder/models.py
franklin/config/settings/base.py
franklin/core/helpers.py
franklin/core/tests.py
franklin/core/urls.py
franklin/core/views.py
franklin/github/api.py
franklin/github/mock_data/api_responses/build.json
franklin/github/mock_data/api_responses/builds.json
franklin/github/mock_data/api_responses/new_site.json
franklin/github/mock_data/api_responses/projects.json
franklin/github/mock_data/github/get_branch.json
franklin/github/mock_data/github/get_repo.json
franklin/github/mock_data/github/get_repos.json
franklin/github/mock_data/github/get_user_orgs.json
franklin/github/tests.py
franklin/github/views.py
franklin/users/models.py
requirements.txt

V1 release

---

franklin/builder/serializers.py
franklin/builder/views.py
franklin/core/urls.py

Connected to #89 
As this is a new endpoint, I assume it is fine to add it to `v1`.
`GET /v1/domains/?domain=example.com`

franklin-server endpoint
